### ISSUE TITLE
Add permalink to about.html front matter

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#17]
Any page outside of the homepage will need a permalink set in the front-matter.

So your about page will look like:

```yml
---
layout: default
permalink: /about/
---
```
