### ISSUE TITLE
Add posts folder

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#19]
Based on our conversation about blogging, will want to add a new folder to the root of your project called `_posts`. This is Jekyll's default post folder.

In that folder you can start creating posts with this naming convention `2018-01-18-learn-css-grid.md`.

Breaking it down you want `[year]-[month]-[day]-[post-title].md`

Then you can start adding posts in this format:

```yaml
---
title: "Learn CSS Grid"
date: 2018-01-18
link: https://cssgrid.io/
---
Great video course about learning CSS Grid by Wes Bos. Excited to dig into this!
```

Feel free to start adding posts, then you can have a solid base of post when you launch the site!
