### ISSUE TITLE
Setup Jekyll project

### ISSUE THREAD

**Issue by alexcarpenter** [emilywestenbroek/emilywestenbroek.github.io#5]
Before starting any of this work, make sure you are working on your newly created `develop` branch you created from issue #4 

1. Install Jekyll following the installation guide https://jekyllrb.com/docs/installation/
2. Create a `_config.yml` file with the following info included 
  
```yaml
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
```

3. Create a folder called `_layouts`
4. Within the newly created `_layouts` folder, create a HTML file called `default.html`
5. Setup your default layout including the following markup:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ site.title }}</title>
</head>
<body>
  {{ content }}
</body>
</html>
```

6. Create your homepage by adding an `index.html` file to the root of your project that includes the following markup

```
---
layout: default
---

<h1>Hello world!</h1>
```

7. Run `jekyll build` from your terminal
8. This should have built your website into a folder called `_site`
9. If number 8 is true push this work to your `develop` branch on Github
